forge "http://forge.puppetlabs.com"


mod 'jfryman-nginx'
mod 'puppetlabs/mysql'
mod 'puppetlabs/apache'

#mod 'wpcli',
#   :git => 'git@github.com:vagrantpress/wpcli.git'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
